### ISSUE TITLE
Sunbelt 2019 workshop testing

### ISSUE THREAD

**Issue by martinamorris** [statnet/Workshops#2] opened 2019-06-03 19:41 UTC
Schedule is:

![image](https://user-images.githubusercontent.com/8194530/58829251-48bb5480-85fc-11e9-897d-ab2a6646cb59.png)

UW will test and update:

workshop | tested | updated |
-- | -- | -- |
ergm | [X] | [ ] | 
tergm | [X] | [ ] | 
ergm.ego | [X] | [ ] | 
valued ergms | [X] | [ ] | 
EUT | [] | [] | 

Others will test and update:

workshop | tested | updated |
-- | -- | -- |
Intro 1 & 2 | [ ] | [ ] | 
Relevent | [ ] | [ ] |

**Comment by mbojan** [comment] 2019-06-03 20:29
@martinamorris which workshop materials do you want me to test&update?

**Comment by martinamorris** [comment] 2019-06-03 20:48
@mbojan i may ask you to review ergm or ergm.ego, but we'll handle the tests/updates.  you've got your own workshop to update :)

**Comment by sgoodreau** [comment] 2019-06-05 12:26
Note that EUT has a unique structure; there is no standard worskhop in script to test, but there are various other tasks to complete (updating the elaborate pre-workshop installation instructions, updating the slides, confirming a correct solution to the coding problem they are given, etc.). Dave and I have a list of these tasks going and are working our way through them, over in the Workshops-Private repository. Will come back here to check this off when they're all done.

**Comment by sgoodreau** [comment] 2019-06-05 12:27
BTW, are there any remaining expected package uploads to CRAN, and if so, what is the expected timeline for that? Would be best to time final testing and updates based on that.

**Comment by chad-klumb** [comment] 2019-06-05 18:46
The possibility of converting the EUT material (at least the ppt) to .Rmd format (for consistency with the other workshops) came up yesterday.

Is that something you and Dave would be interested in having this year, or do you prefer the current ppt?  Or is there not even enough time left at this point (given the different sorts of markup/highlighting/figures the ppt uses vs. the current .Rmd tutorials)?

**Comment by drh20drh20** [comment] 2019-06-05 18:53
Thanks very much for bringing this up, Chad.  In principle I think .Rmd would be great, but I'm a bit wary because I know that quite a bit of the lecture ppt slides involve C code, not R.  This makes the EUT workshop a bit different than the rest of the statnet workshops.  So if there's some way to make it all work somehow I'd love to see it, though my gut reaction is that it's an awful lot to try to tackle for Sunbelt 2019.

**Comment by sgoodreau** [comment] 2019-06-05 19:19
I would *love* to see this done -- but not for 2019.  I have so wiggle room in terms of extra time to devote to this at this point, that even if someone else were to take care of it (say, you), I'm afraid I wouldn't be in a position to deal with any learning curve, no matter how small, nor deal with any issues that might arise.  But I would love to see it converted over the course of the coming year, even starting win the near future.

If you are sitting around without other time sensitive tasks before the workshop and want to give it a try, you can do so, as long as it doesn't somehow hamper our ability to use the tried and true methods we know.  But if so, do wait till I've finished upgrading and checking the existing materials.  The issue is that I probably finish that for some time.....

**Comment by chad-klumb** [comment] 2019-06-11 03:20
we can check "tested" for tergm and valued once PR #4 is merged

**Closed** 2019-06-26 16:10 UTC
Labels: test & update
